### ISSUE TITLE
Could not build the workspace

### ISSUE THREAD

**Issue by sushmitha0708** [ntu-aris/caric#1]
![image](https://github.com/ntu-aris/caric/assets/132066773/3bf7e144-4736-4c45-9009-5d1974a2c14e)

I have followed the steps mentioned in the website but I could not build the workspace. 
I am using Ubuntu 20.04 LTS with ROS Noetic. 
When I am trying to build the CARIAC workspace, only 20 out of 23 packages are getting succeeded. 

Could you please me suggest me a workaround for this?

Thanks in Advance

**Comment by brytsknguyen** [comment]
Hi,

The screenshot may be missing more details. Could you scroll up and find the red "Error" printouts?

 Could you also check what the gazebo version you are using? It can be found in the "About" of the gazebo GUI.

![image](https://github.com/ntu-aris/caric/assets/13504903/aea8dca6-30f2-4251-9a9f-5a56a491130b)

**Comment by sushmitha0708** [comment]
Hello,
Thanks for your reply
I am using Gazebo version 11.13.0
I have uploaded the image showing the error in the terminal 
![Screenshot from 2023-08-22 00-23-52](https://github.com/ntu-aris/caric/assets/132066773/334b33ac-4e37-4dbc-b1ba-4279f8c3aa90)
![Screenshot from 2023-08-22 00-25-33](https://github.com/ntu-aris/caric/assets/132066773/ebb31ea5-9c9e-4c9e-8026-cbe1a1e32379)

**Comment by brytsknguyen** [comment]
Hi,

The screenshot seems to indicate that there is a version mismatch in some fundamental libraries. However we need to see the first error of the output to know which module is asking for which library. Please scroll up further to find the first error that is output by the compiler.

**Comment by sushmitha0708** [comment]
[log.txt](https://github.com/ntu-aris/caric/files/12408591/log.txt)
Please find the error log in the attached file

**Comment by brytsknguyen** [comment]
Hi @sushmitha0708 

I think it is because the system cannot link c++17 libraries to the plugins. I have updated the CMakeLists.txt files to request this explicitly. Could you please run git pull on rotors_simulator and try recompiling?

**Comment by sushmitha0708** [comment]
Thanks a lot @brytsknguyen 
Now it works.
