### ISSUE TITLE
baseline cannot work

### ISSUE THREAD

**Issue by Y1bo-Zhao** [ntu-aris/caric#2]
the process stuck here, I can't deal with the problem
![image](https://github.com/ntu-aris/caric/assets/115137961/597f72d0-8d69-452a-89f3-550af3813b3a)

**Comment by caomuqing** [comment]
Can you describe this more in detail? Is there any error message?

**Comment by Y1bo-Zhao** [comment]
This is the first time I run it
![UMBFL5@8TGPCU61Y@I9~5A_tmb](https://github.com/ntu-aris/caric/assets/115137961/6a3f834e-ef40-4ec7-a351-c61b3d8f415e)

**Comment by Y1bo-Zhao** [comment]
After running the program for the first time, it looks like this
![D`1 6$4UJ8TR{NCA4U6 M2Q_tmb](https://github.com/ntu-aris/caric/assets/115137961/3f87c242-4142-4be0-b264-32d6d67cbd14)

PS:The scarlet letter here also appears on the first run

**Comment by brytsknguyen** [comment]
There are to be multiple issues here. We need to troubleshoot one by one.

First:
![image](https://github.com/ntu-aris/caric/assets/13504903/1c91ddb7-6fd8-4ac4-aa4d-97e7b0eb6e72)

1) can you run the basic program without the caric_baseline?
2) there are errors related to gazebo server crashing, the octomap plugin. Try to install it with `sudo apt install ros-noetic-octomap*`
3) mesh_vizualizer node crashes. Can you go to the script and figure out which line crashes this node?
https://github.com/ntu-aris/caric_mission/blob/master/scripts/mesh_visualizer.py

Second:
![image](https://github.com/ntu-aris/caric/assets/13504903/caa0e1fd-6dec-4a4a-80f2-a5a42088cbb4)
This means that the topic was not registered with ppcomrouter probably.
@xinhangxu996 Does this key error remind you something? I rmb you had to set a delay or something.

**Comment by caomuqing** [comment]
The mesh_vizualizer node crash (the point 3 mentioned by @brytsknguyen ) is caused by this error:
`/usr/bin/env: ‘python’: No such file or directory`
The solution to this problem can be found in the link:
https://stackoverflow.com/questions/3655306/ubuntu-usr-bin-env-python-no-such-file-or-directory

**Comment by brytsknguyen** [comment]
Hi @Y1bo-Zhao,

I have pushed a new commit to caric mission https://github.com/ntu-aris/caric_mission . I think it will solve the problem below, and may let the baseline run. Please try it out and let me know.

![image](https://github.com/ntu-aris/caric/assets/13504903/4f0fec7a-6dad-4a1c-8b08-68e43e7ff2ab)

**Comment by Y1bo-Zhao** [comment]
Thank you very much, after using your suggestions, there was only one error left: Spawn service failed. Exiting. I changed sim_time to 0 in mbs world and the code ran successfully, but it only worked and only detected a few points.
And there is still another problem showing in the third picture.
![image](https://github.com/ntu-aris/caric/assets/115137961/b09775f5-3567-45df-8a83-ad2706aac735)
![image](https://github.com/ntu-aris/caric/assets/115137961/00850dc8-9fe9-45e0-89dc-8285430a48c1)
![image](https://github.com/ntu-aris/caric/assets/115137961/3e28e5c5-3f30-4bcd-8169-9eb54771ca3c)

**Comment by caomuqing** [comment]
Can you check if there is other error message? I think the ppcom node may have crashed.

**Comment by brytsknguyen** [comment]
@Y1bo-Zhao have u been able to run the baseline method? If still stuck maybe we can have a remote desktop session to troubleshoot for you.

**Comment by caomuqing** [comment]
So the issue is caused by nvidia driver not installed. After installing the nvidia driver the program works fine. We have updated the instruction to highlight that.
