### ISSUE TITLE
How to get the LOS matrix?

### ISSUE THREAD

**Issue by Y1bo-Zhao** [ntu-aris/caric#3]
I want to get the judgment condition of whether there is LOS between two agents，and I notice that the video in 6.4 shows a Los matrix. 
Can we get that matrix, or do you have other ways to judge?

**Comment by brytsknguyen** [comment]
Hi @Y1bo-Zhao ,

The LOS is reported in the `/<unit_id>/nbr_odom_cloud`. All neighbours that have line of sight to the unit_id will have the poses put in that pointcloud. The idx of the neighbour can be found in the intensity field.

https://ntu-aris.github.io/caric/#62-onboard-perception-data
